### ISSUE TITLE
Unable to query large polygons 

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/nldi_polygon_query#2]
When testing large fires in https://github.com/USGS-WiM/StreamStats-National/pull/193, I was getting a service error 413 Payload Too Large. 

Example fire near Russell, Kansas: 
![image](https://user-images.githubusercontent.com/40237491/173590211-de9c0e00-c163-4665-a68a-cbaf0495f5cb.png)

I got this error immediately:![image](https://user-images.githubusercontent.com/40237491/173589605-4a94f78e-b564-4b08-92c0-1a85542a6de8.png)

**Comment by aaronstephenson** [comment]
This error came straight from nginx, before the fastapi process was even called.

nginx defaults to a maximum body size of 1MB, so I bumped that up to 64MB for this endpoint (the others on the server are still using the default):
```client_max_body_size 64M;```

**Comment by aaronstephenson** [comment]
With that problem solved, we found another problem: a 500 error saying
>{  "detail": "local variable 'downstreamflowlines' referenced before assignment"}

My initial guess is that the utils.py file, where that variable name occurs, could use some refactoring. I'll take a look tomorrow.

**Comment by Anders-Hopkins** [comment]
Error occurs when get_flowlines=True but downstream_dist = 0. Added an if statement to change get_flowlines to False in this case.

**Comment by Anders-Hopkins** [comment]
Error is originating from https://firehydrology.streamstats.usgs.gov/trace and not nldi-poly-query. Closing issue.
