### ISSUE TITLE
Return gages with nldi_poly_query response

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/nldi_polygon_query#5]
Service work to be completed for https://github.com/USGS-WiM/StreamStats-National/issues/114

**Comment by Anders-Hopkins** [comment]
@amedenblik We are wanting to query NWIS gages, correct?

**Comment by amedenblik** [comment]
@Anders-Hopkins Correct!

**Comment by Anders-Hopkins** [comment]
Developed workflow for requesting NLDI for gages. Met with Andrea and Harper. Decided to use the SS NavigationServices to query gages instead. Looking into a workflow for that.

**Comment by Anders-Hopkins** [comment]
Sketched up a workflow in a Jupyter Notebook for requesting downstream gages from SS NavigationServices. This is achieved by taking the first point (headnode) of each 'outlet' flowline (flowline intersecting with the burned area polygon) and looping thru each point and requesting downstream gages from SS Navigation Services. The results are then combed for duplicate gages, which are inevitable with this method if there are multiple outlet flowlines. 

Gages within the burned are still need to be queried. Best option for this is to use a simplified burned area polygon in a NLDI query. Another possibility is to loop thru catchment comids (catchments which overlap the burned area), request gages with these comids, and only keep gages which fall in the burned area polygon.

**Comment by Anders-Hopkins** [comment]
Can get donwstream gages from StreamStats Navigation Service, and can get gages inside the fire polygon with GageStats. Working these requests into the nldi_polygon_query service.

**Comment by amedenblik** [comment]
Hi Anders, we realized that we moved the NLDI polygon query service from https://nldi-polygon-query.streamstats.usgs.gov/ to https://streamstats.usgs.gov/nldipolygonservices/. Can you please update the service at https://streamstats.usgs.gov/nldipolygonservices/ to include the new nldi_poly_query_new endpoint?

**Comment by amedenblik** [comment]
@Anders-Hopkins We are ready to merge in https://github.com/USGS-WiM/StreamStats-National/pull/262. Can you please rename the `nldi_poly_query_new` endpoint to `nldi_poly_query` and let us know when complete? Thanks!

**Comment by Anders-Hopkins** [comment]
@amedenblik Renamed the service nldi_poly_query, redeployed the service, tested it and it works as expected.
